"use client";

import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { 
  Bot, 
  Video, 
  MessageSquare, 
  Search, 
  ShieldCheck,
  Zap,
  ArrowRight
} from "lucide-react";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-primary/20">
      {/* Nav */}
      <nav className="flex items-center justify-between p-6 max-w-7xl mx-auto">
        <h1 className="text-2xl font-bold bg-gradient-to-r from-primary to-blue-600 bg-clip-text text-transparent">
          Antigravity AI
        </h1>
        <div className="flex items-center gap-6">
          <Link href="/login" className="text-sm font-medium hover:text-primary transition-colors">Login</Link>
          <Button asChild className="rounded-full px-6">
            <Link href="/register">Get Started Free</Link>
          </Button>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-24 pb-16 px-6 text-center max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <span className="px-4 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-semibold mb-6 inline-block">
            100% Local AI Intelligence
          </span>
          <h2 className="text-5xl md:text-7xl font-bold tracking-tight mb-8 leading-[1.1]">
            Turn your meetings into <br />
            <span className="bg-gradient-to-r from-blue-500 via-primary to-purple-500 bg-clip-text text-transparent">
              Actionable Intelligence
            </span>
          </h2>
          <p className="text-xl text-muted-foreground mb-10 max-w-2xl mx-auto">
            Transcribe, summarize, and chat with your meeting history. All data stays on your machine. No APIs, no privacy leaks.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button asChild size="lg" className="h-14 px-8 rounded-full text-lg gap-2 shadow-xl shadow-primary/20">
              <Link href="/register">
                Get Started <ArrowRight size={20} />
              </Link>
            </Button>
            <Button variant="outline" size="lg" className="h-14 px-8 rounded-full text-lg">
              View Demo
            </Button>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section className="py-24 px-6 max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
        {[
          { icon: Video, title: "Smart Transcription", desc: "Powered by Whisper.cpp for industry-leading accuracy on your hardware." },
          { icon: Bot, title: "AI Summaries", desc: "Instant key points, decisions, and action items generated by Llama 3." },
          { icon: MessageSquare, title: "RAG Chat", desc: "Ask questions across your entire meeting history with deep context." },
          { icon: Search, title: "Semantic Search", desc: "Find meetings based on concepts and meaning, not just exact keywords." },
          { icon: ShieldCheck, title: "Privacy First", desc: "No data ever leaves your machine. 100% local processing." },
          { icon: Zap, title: "Instant Action", desc: "Automatically sync tasks to your favorite project management tools." },
        ].map((feat, i) => (
          <motion.div
            key={feat.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1 }}
            className="p-8 rounded-3xl border bg-card/50 backdrop-blur-xl hover:border-primary/50 transition-all group"
          >
            <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary mb-6 group-hover:scale-110 transition-transform">
              <feat.icon size={24} />
            </div>
            <h3 className="text-xl font-bold mb-3">{feat.title}</h3>
            <p className="text-muted-foreground leading-relaxed">{feat.desc}</p>
          </motion.div>
        ))}
      </section>
    </div>
  );
}
